# pipeline-main.yml

name: Build Main

on:
  push:
    branches: [ main ]

jobs:
  aab:
    name: Generate AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build AAB
        run: bash ./gradlew bundle assemble --stacktrace
      - name: Upload AAB
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: androidApp/build/outputs/bundle/
  upload:
    name: Upload AAB
    needs: aab
    runs-on: ubuntu-latest
    steps:
      - name: Download AAB from build
        uses: actions/download-artifact@v1
        with:
          name: aab
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: r${{ github.run_number }}
          release_name: r${{ github.run_number }}
      - name: Upload Release AAB
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aab/release/androidApp-release.aab
          asset_name: app-release-${{ github.run_number }}.aab
          asset_content_type: application/zip
      - name: Upload Debug AAB
        id: upload_debug_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aab/debug/androidApp-debug.aab
          asset_name: app-debug-${{ github.run_number }}.aab
          asset_content_type: application/zip
