# pipeline-main.yml

name: Build Main

on:
  push:
    branches: [ main ]

jobs:
  aab:
    name: Generate AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build AAB
        run: bash ./gradlew bundleRelease
        
      - name: Sign AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: androidApp/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}

      - name: Upload AAB
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
  upload:
    name: Upload AAB
    needs: aab
    runs-on: ubuntu-latest
    steps:
      - name: Download AAB from build
        uses: actions/download-artifact@v1
        with:
          name: aab
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: r${{ github.run_number }}
          release_name: r${{ github.run_number }}
      - name: Upload Release AAB
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aab/androidApp-release.aab
          asset_name: app-release-${{ github.run_number }}.aab
          asset_content_type: application/zip