# pipeline-pull-request.yml

name: Build Pull Request

on:
  pull_request:
    branches:
      - '!main'
      - '!development'
      - '*'

jobs:
  tests:
    name: Run Ktlint and Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Ktlint check
        run: ./gradlew ktlintCheck
      - name: Unit tests
        run: ./gradlew test --stacktrace