# pipeline-development.yml

name: Build Development

on:
  push:
    branches: [ development ]

jobs:
  build:
    name: Generate AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build AAB
        run: bash ./gradlew bundleDebug --stacktrace

      - name: Upload AAB
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: androidApp/build/outputs/bundle/debug/androidApp-debug.aab

  upload:
    name: Upload AAB
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download AAB from build
        uses: actions/download-artifact@v1
        with:
          name: aab
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: v${{ github.run_number }}
      - name: Upload AAB
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aab/androidApp-debug.aab
          asset_name: androidApp-debug-${{ github.run_number }}.aab
          asset_content_type: application/zip
